/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuteurReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "auteur";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titre?: string;
  slug?: Slug;
  rubrique?:
    | "politique"
    | "economie"
    | "societe"
    | "diplomatie"
    | "sante"
    | "environnement"
    | "developpement-durable"
    | "education"
    | "arts-culture-traditions"
    | "litterature"
    | "portrait";
  chapo?: string;
  extrait?: string;
  corps?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  imagePrincipale?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    legende?: string;
    _type: "image";
  };
  citation?: string;
  auteur?: AuteurReference;
  publieLe?: string;
  aLaUne?: boolean;
};

export type Auteur = {
  _id: string;
  _type: "auteur";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  role?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AuteurReference
  | Article
  | Auteur
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: ARTICLE_A_LA_UNE_QUERY
// Query: *[_type == "article" && aLaUne == true] | order(publieLe desc) [0] {    "slug": slug.current,    rubrique,    titre,    chapo,    "auteur": auteur->nom,    "publieIl_y_a": publieLe,    "image": imagePrincipale{    "legende": legende,    "url": asset->url,    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height  },    aLaUne  }
export type ARTICLE_A_LA_UNE_QUERY_RESULT = {
  slug: string | null;
  rubrique:
    | "arts-culture-traditions"
    | "developpement-durable"
    | "diplomatie"
    | "economie"
    | "education"
    | "environnement"
    | "litterature"
    | "politique"
    | "portrait"
    | "sante"
    | "societe"
    | null;
  titre: string | null;
  chapo: string | null;
  auteur: string | null;
  publieIl_y_a: string | null;
  image: {
    legende: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  } | null;
  aLaUne: true;
} | null;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: ARTICLES_SECONDAIRES_QUERY
// Query: *[_type == "article" && aLaUne != true] | order(publieLe desc) [0...$limit] {    "slug": slug.current, rubrique, titre, "publieIl_y_a": publieLe,    "image": imagePrincipale{    "legende": legende,    "url": asset->url,    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height  }  }
export type ARTICLES_SECONDAIRES_QUERY_RESULT = Array<{
  slug: string | null;
  rubrique:
    | "arts-culture-traditions"
    | "developpement-durable"
    | "diplomatie"
    | "economie"
    | "education"
    | "environnement"
    | "litterature"
    | "politique"
    | "portrait"
    | "sante"
    | "societe"
    | null;
  titre: string | null;
  publieIl_y_a: string | null;
  image: {
    legende: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  } | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: ARTICLES_PAR_RUBRIQUE_QUERY
// Query: *[_type == "article" && rubrique == $rubrique && aLaUne != true]    | order(publieLe desc) [0...$limit] {    "slug": slug.current, rubrique, titre, extrait,    "publieIl_y_a": publieLe,    "image": imagePrincipale{    "legende": legende,    "url": asset->url,    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height  }  }
export type ARTICLES_PAR_RUBRIQUE_QUERY_RESULT = Array<{
  slug: string | null;
  rubrique:
    | "arts-culture-traditions"
    | "developpement-durable"
    | "diplomatie"
    | "economie"
    | "education"
    | "environnement"
    | "litterature"
    | "politique"
    | "portrait"
    | "sante"
    | "societe"
    | null;
  titre: string | null;
  extrait: string | null;
  publieIl_y_a: string | null;
  image: {
    legende: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  } | null;
}>;

// Source: ../web/src/lib/sanity/queries.ts
// Variable: PORTRAIT_EN_AVANT_QUERY
// Query: *[_type == "article" && rubrique == "portrait"] | order(publieLe desc) [0] {    citation,    "nom": auteur->nom,    "role": auteur->role,    extrait,    "slug": slug.current,    "image": imagePrincipale{    "legende": legende,    "url": asset->url,    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height  }  }
export type PORTRAIT_EN_AVANT_QUERY_RESULT = {
  citation: string | null;
  nom: string | null;
  role: string | null;
  extrait: string | null;
  slug: string | null;
  image: {
    legende: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "article" && aLaUne == true] | order(publieLe desc) [0] {\n    "slug": slug.current,\n    rubrique,\n    titre,\n    chapo,\n    "auteur": auteur->nom,\n    "publieIl_y_a": publieLe,\n    "image": imagePrincipale{\n    "legende": legende,\n    "url": asset->url,\n    "width": asset->metadata.dimensions.width,\n    "height": asset->metadata.dimensions.height\n  },\n    aLaUne\n  }\n': ARTICLE_A_LA_UNE_QUERY_RESULT;
    '\n  *[_type == "article" && aLaUne != true] | order(publieLe desc) [0...$limit] {\n    "slug": slug.current, rubrique, titre, "publieIl_y_a": publieLe,\n    "image": imagePrincipale{\n    "legende": legende,\n    "url": asset->url,\n    "width": asset->metadata.dimensions.width,\n    "height": asset->metadata.dimensions.height\n  }\n  }\n': ARTICLES_SECONDAIRES_QUERY_RESULT;
    '\n  *[_type == "article" && rubrique == $rubrique && aLaUne != true]\n    | order(publieLe desc) [0...$limit] {\n    "slug": slug.current, rubrique, titre, extrait,\n    "publieIl_y_a": publieLe,\n    "image": imagePrincipale{\n    "legende": legende,\n    "url": asset->url,\n    "width": asset->metadata.dimensions.width,\n    "height": asset->metadata.dimensions.height\n  }\n  }\n': ARTICLES_PAR_RUBRIQUE_QUERY_RESULT;
    '\n  *[_type == "article" && rubrique == "portrait"] | order(publieLe desc) [0] {\n    citation,\n    "nom": auteur->nom,\n    "role": auteur->role,\n    extrait,\n    "slug": slug.current,\n    "image": imagePrincipale{\n    "legende": legende,\n    "url": asset->url,\n    "width": asset->metadata.dimensions.width,\n    "height": asset->metadata.dimensions.height\n  }\n  }\n': PORTRAIT_EN_AVANT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
